services:
  - type: web
    name: ellison-fullstack
    rootDir: ./
    env: node
    region: frankfurt
    buildCommand: |
      cd ./
      npm install
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: UPLOAD_DIR
        value: /app/uploads
    disk:
      name: uploads
      mountPath: /app/uploads
